services:
  magic_pinecone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic_pinecone_backend
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - apim_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  digirunner:
    image: tpisoftwareopensource/digirunner-open-source:release-v4.7.3
    container_name: digirunner_gateway
    ports:
      - "18080:18080"
    networks:
      - apim_network
    depends_on:
      - magic_pinecone
    restart: unless-stopped

  db:
    image: postgres
    container_name: magic_pinecone_db
    environment:
      POSTGRES_USER: magic_user
      POSTGRES_PASSWORD: magic_password
      POSTGRES_DB: magic_pinecone
    ports:
      - "5432:5432"
    networks:
      - apim_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U magic_user -d magic_pinecone" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  apim_network:
    driver: bridge
