version: '3.8'

services:
  magic_pinecone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic_pinecone_backend
    expose:
      - "8000"

    ports:
      - "8000:8000"
    networks:
      - apim_network
    restart: unless-stopped

  digirunner:
    image: tpisoftwareopensource/digirunner-open-source:release-v4.7.3
    container_name: digirunner_gateway
    ports:
      - "18080:18080"
    networks:
      - apim_network
    depends_on:
      - magic_pinecone
    restart: unless-stopped

networks:
  apim_network:
    driver: bridge
